### ISSUE TITLE
在第二次运行之后提示上次已完成所有shopid，选择1重新跑一次之后就没有反应了，这是什么原因呢？我把memory设置成False问题依然存在

### ISSUE THREAD

**Issue by yemingjkl** [curtinlv/JD-Script#10]
[2021-05-24 22:50:39]: 已在后台运行 PID：root 如需要终止执行命令：kill root
[2021-05-24 22:50:39]: 查看运行日志: tail -f /jd/opencard/run_OpenCard.log
root@15d120a61893:/jd/opencard $ tail -f /jd/opencard/run_OpenCard.log
上次已完成所有shopid，

Ps:您可以关注公众号或TG频道获取最新shopid。
公众号: TopStyle
电报TG:https://t.me/TopStyle2021

请输入 0 或 1
0 : 退出。
1 : 重新跑一次，以防有漏
正在等待您的选择：1

**Comment by yemingjkl** [comment]
我删除.log文件后重新新建.log 后能正常运行

**Comment by curtinlv** [comment]
如果用start.sh执行，你配置参数填在OpenCardConfig.ini 还是 start.sh 里面？sh start.sh 只会读取start.sh里面的参数。OpenCardConfig.ini 参数无效。

**Comment by yemingjkl** [comment]
> 如果用start.sh执行，你配置参数填在OpenCardConfig.ini 还是 start.sh 里面？sh start.sh 只会读取start.sh里面的参数。OpenCardConfig.ini 参数无效。
我在start.sh里配置的 运行的是sh start.sh

**Comment by yemingjkl** [comment]
似乎问题没有再现

**Comment by Sherwin-Wang** [comment]
> 如果用start.sh执行，你配置参数填在OpenCardConfig.ini 还是 start.sh 里面？sh start.sh 只会读取start.sh里面的参数。OpenCardConfig.ini 参数无效。

膜拜大佬。大佬今早没有更新shopid?
