### ISSUE TITLE
V4用户的关注有礼的通知变量如果也能读取入会脚本里面的变量就好了。

### ISSUE THREAD

**Issue by douzicao** [curtinlv/JD-Script#23]
要不然每次下载后就覆盖掉了。

**Comment by sola237** [comment]
> 要不然每次下载后就覆盖掉了。

兄弟你的V4是怎么运行python的？我普通的v4提示找不到python3，现在bot又拉不了了

**Comment by curtinlv** [comment]
已更新

**Comment by douzicao** [comment]
> > 要不然每次下载后就覆盖掉了。
> 
> 兄弟你的V4是怎么运行python的？我普通的v4提示找不到python3，现在bot又拉不了了

我的直接就能。。你装一下依赖，按照BOT的里面依赖装。

**Comment by douzicao** [comment]
> 已更新

多谢

**Comment by sola237** [comment]
> > > 要不然每次下载后就覆盖掉了。
> > 
> > 
> > 兄弟你的V4是怎么运行python的？我普通的v4提示找不到python3，现在bot又拉不了了
> 
> 我的直接就能。。你装一下依赖，按照BOT的里面依赖装。

我装的是普通版本的V4，能直接在容器里面装的了python吗？
