### ISSUE TITLE
如果加到crontab里面，路径会有问题，麻烦修改一下

### ISSUE THREAD

**Issue by qqwas** [curtinlv/JD-Script#3]
这是我从网上找到的文章https://www.cnblogs.com/jacksonkwong/p/11631078.html

下面是日志

开始执行...
Wed May 19 2021 21:09:44 GMT+0800 (中国标准时间)
参数配置有误，请检查OpenCardConfig.ini
Error: No section: 'main'
尝试从Env环境获取！
[OpenCardConfig.ini] 和 [Env环境] 都无法获取到您的参数或缺少，请配置!
Error: name 'cookies' is not defined

执行结束...

**Comment by curtinlv** [comment]
ok

**Comment by curtinlv** [comment]
你也可以使用 export  加载变量，写到 vi ~/.bash_profile
export JD_COOKIE='pt_key=xxx;pt_pin=xxx;' 
export openCardBean=30
export xxx=xxx

**Comment by qqwas** [comment]
谢谢

**Comment by qqwas** [comment]
我试了一下，写了一个脚本
#/bin/bash                                                                                  
cd /u01/JD-Script/OpenCrad/                                                                 
python3  /u01/JD-Script/OpenCrad/jd_OpenCrad.py 
也解决问题了。
还有一个问题请教一下，脚本本身不自动更新吗
