### ISSUE TITLE
你好昨天更新之后跑的全报错改延时改1了还是不行

### ISSUE THREAD

**Issue by knowledgeablelmh** [curtinlv/JD-Script#32]
![微信截图_20210615125129](https://user-images.githubusercontent.com/83534987/121994920-bba95980-cdd8-11eb-9705-00e502f7b6fd.png)
![微信截图_20210615125501](https://user-images.githubusercontent.com/83534987/121995280-4427fa00-cdd9-11eb-8a3f-dc59afbea219.png)

**Comment by yftu** [comment]
遇到同样问题，等待大佬修正吧

**Comment by XjCaoer** [comment]
等待大佬修正~

**Comment by alanleung2017** [comment]
+1

**Comment by FKDD23** [comment]
+1
