### ISSUE TITLE
Env参数如何填写

### ISSUE THREAD

**Issue by Chicuang** [curtinlv/JD-Script#4]
如何不依赖ini文件运行py

**Comment by curtinlv** [comment]
env环境配置
export 变量名称=值
export JD_COOKIE='pt_key=xxx;pt_pin=xxx;' (多账号&分隔)
export openCardBean=30
export xxx=yyy
或
docker-compose 环境 可以写在: docker-compose.yml
volumes:
    -  JD_COOKIE=pt_key=xxx;pt_pin=xxx;
    -  openCardBean=30
    -  xxx=yyy

**Comment by Chicuang** [comment]
export 变量直接填写到py文件配置中吗

**Comment by curtinlv** [comment]
已更新 start.sh ，配置这个执行就可以了。
定时任务 也是执行这个sh start.sh

**Comment by Chicuang** [comment]
感谢

**Comment by HailPHP** [comment]
> 已更新 start.sh ，配置这个执行就可以了。
> 定时任务 也是执行这个sh start.sh

执行start.sh时提示
nohup: ignoring input
nohup: failed to run command 'python3': Permission denied
这个权限怎么设置呢？
