### ISSUE TITLE
zjd.py一直报错

### ISSUE THREAD

**Issue by Annyoo2021** [curtinlv/JD-Script#45]
export zlzh=[20%E5%B9%B4%E6%B3%A886%8C','%E6%A8%E8%89%BA%E6%81%9']
##以上变量填的pt_pin.

执行报错：
python3 /jd/scripts/jd_zjd.py
当前环境V4
微信小程序-赚京豆-瓜分助力
您已配置27个账号
账号1【xxxx】Cookie 已失效！请重新获取。
请检查助力账号名称是否正确？提示：助力名字可填pt_pin的值、也可以填用户名。

另：scripts文件夹没有 JDCookies.txt，不知道是不是因为这个。
脚本最新的，变量也试过改成昵称，也不行。变量后面 加单引号 双引号各种，一样报错。cookies都没有失效。
求解

**Comment by Annyoo2021** [comment]
zlzh = ['aaaaa', '买买买', '东哥']

直接修改脚本里的，可以运行，改成用户名，昵称，都可以。变量就是不行

**Comment by lqrqw** [comment]
> zlzh = ['aaaaa', '买买买', '东哥']
> 
> 直接修改脚本里的，可以运行，改成用户名，昵称，都可以。变量就是不行

同v4，确实只能改脚本的。不过也能用，谢谢提供解决方法

**Comment by bargaindr** [comment]
> > zlzh = ['aaaaa', '买买买', '东哥']
> > 直接修改脚本里的，可以运行，改成用户名，昵称，都可以。变量就是不行
> 
> 同v4，确实只能改脚本的。不过也能用，谢谢提供解决方法

咋改啊 改哪个地方呢

**Comment by w13689226302** [comment]
对，v4只能在py脚本写死助力，。加在config.sh里的不识别
