### ISSUE TITLE
怎么配合配合crontab 坐等收豆？

### ISSUE THREAD

**Issue by lanyucomputer** [curtinlv/JD-Script#5]
望出一下教程，怎么配合配合crontab 坐等收豆，这个可以DOCKER吗

**Comment by curtinlv** [comment]
Docker可以跑，迟点有空在公众号出个教程。

**Comment by pompeyY** [comment]
+1  没找到教程哈。能再docker自己跑就完美了

**Comment by lanyucomputer** [comment]
现在每天都没有豆了，要不就入会没有豆，要不就是已经是会员了，不知道你们情况怎么样

**Comment by pompeyY** [comment]
> 现在每天都没有豆了，要不就入会没有豆，要不就是已经是会员了，不知道你们情况怎么样

有 但很少豆

**Comment by alanleung2017** [comment]
跪求docker部署方式，配置crontab使用

**Comment by pompeyY** [comment]
跪求docker部署方式，配置crontab使用
