### ISSUE TITLE
jd_qjd 脚本遇到pt_pin为中文转码的cookie账跳出操作

### ISSUE THREAD

**Issue by snakeleon** [curtinlv/JD-Script#50]
行为表现：检查ck有效性处，如遇到用户ck格式中pt_pin是中文编码转意形式的（早期中文注册的账号，非jd_xxxxxx形式），会跳过该ck操作。有效ck在本活动中无法参加，望请修复编码形式引起误判断ck无效的这个问题！

**Comment by curtinlv** [comment]
已修复

**Comment by snakeleon** [comment]
问题解决，感谢及时修复！
