### ISSUE TITLE
local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by EchoChan314** [curtinlv/JD-Script#51]
tg服务启动
推送失败！
local variable 'response' referenced before assignment

而且是随机出现的问题，python执行会出现这种情况，start.sh执行也可能出现这种情况，不管是windows平台，还是termux都出现过这种情况。

**Comment by curtinlv** [comment]
这可能是你的网络问题或节点问题。




| |
Curtin
|
|
***@***.***
|

Signature is customized by Netease Mail Master

On 07/14/2021 11:12, Echo Chan wrote:

tg服务启动
推送失败！
local variable 'response' referenced before assignment

而且是随机出现的问题，python执行会出现这种情况，start.sh执行也可能出现这种情况，不管是windows平台，还是termux都出现过这种情况。

**Comment by EchoChan314** [comment]
ok，我后续不用TG推送试试。
