### ISSUE TITLE
V4环境中,config.sh中的export环境变量如果带有!会导致正则异常卡住

### ISSUE THREAD

**Issue by tmsdy** [curtinlv/JD-Script#61]
export tytpacketId="27350e27f5af46208a300d373d339cf0-NjcyNTM2MDQtNjkyMTkzOTg!"

导致异常的参数.   需要在正则匹配中加上一个 !  

![quicker_9e1fc5d1-4cb7-4680-99cd-06c8f15d5404.png](https://i.loli.net/2021/07/24/coRbX21qwUaWsLi.png)

**Comment by curtinlv** [comment]
好的，我加上试试，谢谢反馈。

**Comment by curtinlv** [comment]
还是有人反馈会卡住。我没有v4环境，但模拟读取config.sh又是没有问题。

**Comment by sxx1314** [comment]
满尴尬的，实测专门为了v4特殊处理的这部分代码删掉就能正常无障碍运行。
https://github.com/curtinlv/JD-Script/blob/3b49cf45d3563598321af14ac260fe8ece4e74e1/jd_qjd.py#L268-L281
