### ISSUE TITLE
TG BOT TOKEN 是必填项目吗？报这个错是什么原因呢？

### ISSUE THREAD

**Issue by yemingjkl** [curtinlv/JD-Script#7]
已获取并使用Env环境 sleepNum: 0.0
已获取并使用Env环境 printlog: False
已获取并使用Env环境 record: True
已获取并使用Env环境 onlyRecord: False
已获取并使用Env环境 memory: True
已获取并使用Env环境 isRemoteSid: False
Traceback (most recent call last):
  File "jd_OpenCrad.py", line 272, in <module>
    elif not TG_BOT_TOKEN:
NameError: name 'TG_BOT_TOKEN' is not defined

**Comment by yemingjkl** [comment]
我自行讲jd_opencard.py里 tg相关的代码屏蔽之后能够正常运行了

**Comment by curtinlv** [comment]
已修复
