### ISSUE TITLE
大佬能增加个变量把cookie有效性校验去了吗

### ISSUE THREAD

**Issue by abcdol** [curtinlv/JD-Script#76]
有些服务器ip被那个检测有效性的接口拉黑了，直接返回403或者空，cookie实际是有效的，直接全部跑不了😂😂

**Comment by curtinlv** [comment]
好的




| |
Curtin
|
|
***@***.***
|

Signature is customized by Netease Mail Master

在2021年11月08日 16:59，abcdol 写道：

有些服务器ip被那个检测有效性的接口拉黑了，直接返回403或者空，cookie实际是有效的，直接全部跑不了😂😂

**Comment by abcdol** [comment]
感谢大佬～
