### ISSUE TITLE
有依赖脚本cookie py运行环境监测正常，运行助力脚本仍然提示没依赖要下载脚本

### ISSUE THREAD

**Issue by fenglatiao** [curtinlv/JD-Script#78]
有依赖脚本cookie py运行环境监测正常，运行助力脚本仍然提示没依赖要下载脚本

**Comment by monkey-sking** [comment]
同样的问题不知道怎么解决

**Comment by EchoChan314** [comment]
单独下载jd_cookie.py并保持文件名为jd_cookie.py

**Comment by curtinlv** [comment]
更新仓库脚本jd_tool_dl.py，执行会自动下载依赖。

**Comment by fenglatiao** [comment]
![image](https://user-images.githubusercontent.com/66894485/141220573-3fa0de8b-cef2-43c3-ac46-d45bc7ee639a.png)
修复了可以了现在推送不对了这是啥原因啊
