### ISSUE TITLE
“关注有礼”Cookie 已失效！请重新获取。

### ISSUE THREAD

**Issue by agigogo** [curtinlv/JD-Script#84]
其他脚本运行没问题，就是这个getFollowGift.py老提示Cookie 已失效！请重新获取。

“#cookie填写，注意：#ck 优先读取【JDCookies.txt】 文件内的ck  再到 ENV的 变量 JD_COOKIE='ck1&ck2' 最后才到脚本内 cookies=ck”

我特意在JDCookies.txt里填写了ck,但还是提示已获取并使用Env环境

不知道怎么才能解决这个问题。

**Comment by zhiping128** [comment]
我的也是一样的问题

**Comment by agigogo** [comment]
突然又变好了，又能正常运行了。只不过都是0豆。

**Comment by zhiping128** [comment]
嗯，重新下载可以了，有几个豆子




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "curtinlv/JD-Script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [curtinlv/JD-Script] “关注有礼”Cookie 已失效！请重新获取。 (Issue #84)





 
突然又变好了，又能正常运行了。只不过都是0豆。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
